/** แผนที่ชื่อไอคอน -> component lucide — จุดเดียวสำหรับ component ที่รับชื่อ icon เป็น string
 *  ชื่อ key คงรูปแบบ Feather เดิมไว้เพื่อให้ call site ไม่ต้องแก้ แต่ตัวที่วาดคือ lucide ทั้งหมด */
import {
  Activity,
  Award,
  BarChart2,
  Bell,
  Bookmark,
  Calendar,
  Camera,
  Check,
  CheckCircle,
  ChevronLeft,
  ChevronRight,
  Clock,
  Coffee,
  Droplet,
  Eye,
  EyeOff,
  FileText,
  Heart,
  HelpCircle,
  Image,
  Info,
  Layers,
  Lock,
  LogOut,
  Mail,
  MapPin,
  Pencil,
  Phone,
  Plus,
  RefreshCw,
  Settings,
  Target,
  Trash2,
  User,
  X,
} from "lucide-react-native";

const MAP = {
  activity: Activity,
  award: Award,
  "bar-chart-2": BarChart2,
  bell: Bell,
  bookmark: Bookmark,
  calendar: Calendar,
  camera: Camera,
  check: Check,
  "check-circle": CheckCircle,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  clock: Clock,
  coffee: Coffee,
  droplet: Droplet,
  "edit-2": Pencil,
  pencil: Pencil,
  eye: Eye,
  "eye-off": EyeOff,
  "file-text": FileText,
  heart: Heart,
  "help-circle": HelpCircle,
  image: Image,
  info: Info,
  layers: Layers,
  lock: Lock,
  "log-out": LogOut,
  mail: Mail,
  "map-pin": MapPin,
  phone: Phone,
  plus: Plus,
  "refresh-cw": RefreshCw,
  settings: Settings,
  target: Target,
  "trash-2": Trash2,
  user: User,
  x: X,
};

/** รับทั้งชื่อ (string) หรือ lucide component ตรงๆ — คืน component ที่วาดได้ หรือ null */
export function resolveIcon(name) {
  if (!name) return null;
  if (typeof name === "function") return name;
  return MAP[name] || null;
}
